language: node_js
node_js:
- '12'
sudo: false
git:
  submodules: false
branches:
  only:
  - master
before_script: make init
script: make build
deploy:
- provider: script
  script: make release
  on:
    branch: master
- provider: script
  script: curl -X POST -d {} https://api.netlify.com/build_hooks/5d53b7e5c624e4e570256c69
  on:
    branch: master
env:
  global:
