language: node_js
node_js:
- '12'
sudo: false
git:
  submodules: false
branches:
  only:
  - master
before_script: make init
script: make travis-deploy
deploy:
- provider: script
  script: make release
  on:
    branch: master
- provider: script
  script: curl -X POST -d {} https://api.netlify.com/build_hooks/5d53b7e5c624e4e570256c69
  on:
    branch: master
env:
  global:
  - secure: HGa0zqq0/dbI6UsjT+uhPuyZlOn1KE1W2eybH2gyo7ymEJ+I1Caklvp3PQ7kBtVilUDSp5vcyWPj5HTvIHsRec8CZmu15Uoo7OkKvwW6SKoe6ahicZ0osTd5xSKxmLzwZt1uksFDMJ+qSpo/V8Je6F/WiC9HRAmGvk2uBuxqhexaL72UH57w2C1UzlOWOv8S9EOm0IQIjKSOYJa24KvveOXy+yZqQMrvafLJy0zomeElgL9FpBoFDZ42MH49HZzs1GfhrrIGYpu34TWzlKnG7C1+XB1YF7Ib3EzPwA3WL/8nXxIvyB1Gb7HQ3j63Xul7jRX5EC89nKhiJQBhpEPnNeJfBiB9yDMSv5hzfOdSMqAIAZVWC/xznM3HOPeXspAxqqFdhQh62MEOZUlasmmgeUFykMmB7+dHaSTGLPSuQOLnr3IyrTzODZsR+gaGmEWIQpMxlph8UORbEA04MMkiT66I8KPQeI3qE+TAedxvy0CPfff61B7NmgQyHL61raeRWk9AKTVqvdhZ2kgT5BnPjgQNw/MafBRADnecxJerZQzBqZAbglO5/k/XaSa6JrEMnoWIQ57GC48uKK6/BTeYR+QxDmWxKoD9wFXOeALALbq9dsAcjWe/KgjZ5MKfaSVrekRDWutbHy7aD2D6q442BiV3baytdO0qaxyt3bAl6N0=
  - secure: ErotrzLHlGB+ceZq6ak+W4iXpx2EWueXoTUf1UmxX362fLGm73buc3kDse7QCgVp/IwUaT1WUSK89S62B/oE7Q503xVIIBfa8lgdaxm2G7g8Zl5W0xT6O1R2ocGGr+eG4N0PRHsMax5TJ8cbkAyoX3H8vzKNZuY5OIQifQfPZX/UBZjxsOjEDchIuukO2wokowuacuQCvTGKma2iNyjCgDalj4BPnD3IDnAdO/nzzbNkM//6n+2R6ghw3dq+7hANcUY4B5trzBid8iZvfZtH/GXxpBIqY+OH9qEkoFZBphUaRhzWpZzWV3/aU41aKaWESlzd+PDDCm0//uaHr3ZUp/TrP40LYnQv56AevXmX7PX8D2jtJGBzXY+u7AS84rSretbdkibMZYO0YGQzBm/whxa/loKhQtqrf/UX094VBrj6FsR6KDPYshPsj6iS8JN4oqvZX6Efrc6gtBiEu83VclRHRm9lQLK0dKJEZ8176r57Ht3jkGHbjeWghaIhVhYTjqU2aZKZom98Z7W+MMqVlcTwiQnMrhLdF+R3NXDAt9TnlWblrDl0YXf81/BDC5qC5noFytYAej1Fttdidmd6qIvnKLeHJMlUb9o1CChvv6ibMU9EnzUksnzqGCYT4VNAeqatWuoTpODXyB4Mzyf9q3T1BJCgEO8PPffvrx5c2eY=
  - secure: r7a2VG2wE6bXV7zjpyVpKThA4MGBGy4p3yZcgtIcPx8qA5mR8dN4fOsQec3MTJtqhVjyyItbFdx8WqR+e8rnO+9kHJIium6xRoE7d6FfTUrmWpW8xYoRDijDncn5ObEO1E/7chDYJq6jOOvIXkOdBo54SWZI/SjnQ2EIRGkCYiREVa/7Wh8dZ3cfFIgtxsKyiKWYGE/sPA2j4c0tOs74xRXlRDO4yAMGc0eMslwazp/946lNQ83DLW9HPKJXcSqNIKOz54GO5m55cJ1xO0juDQH9LBkR943Sd2ODHafMuIWPvr2cS7v8ZTskGh6INFSZI2p1bITZaRTpuDa1lUJpany0U40/uO1t8CZhKQoSwx/LMhRhAHFx807tkw84tvt/CUtHo9oAdcyQB/dXOg/xhUurNo17lzgwrUsWIEfI3zjttkVU7PDOSXgiY8x9t2yfPAIRzJpjDq4zGHkuu53s5dq0fxKKrycV9sy9/kdT0HpwbnIfQkMtuG8Qpd/8UR4wuUUiglAPi9xjYism8uvG0i04LTsN26UGg7YijUOup7TeCApE8sGFjxDWNkfEts1SHH4cOCtLmXfUXGfxDj3oxm8K76csO5yd37zPRTf2Y8gsUZz8dH17SPOBRmh2rhvvHZ7suDbCwHwyjOYKCn9CsGKWDYAw45KiC2ypT4lDHRM=
  - secure: YNV1vvJKr4nYUza1xaUw+ME7kGIka9LaVENwdAEkDHbe0AODcX71GdQICOkUeofln/nkY3MDeQjczVeytv70A1IQJ2eiyZBUPIA7R8f4JL27aht4d+n122IiKBYaS92HvL6FsLUhdWAd9VCZDOgoJ/JfsNVBrK0AjR/8JEDeHoMSaPp1b52w9siSxFOZ81pmj1ytyDdqeZW+h6xODS5B+jWbrpOAJbY66WLX7lhGp2HWuV1u32xXhmYqas9eFgcdpkANG6vrgNyxkJGR4CUxiJwvwGO65Y1oBvGBH3yyYsLHgo14qpVaClmTbzHCcuJlrZBmPkK5RCj+QirUPwEFGlnDIt8HmdUm12WBBhWsJM9PTCm/wmyzfrKpPdwbntELDm/lGM5xew9+sQEG13Z88u5stOOTbgLBjKLqiJ6uIobyxszPokYgbo2uyIv8cJvBDZMng9Gz/lhcfphyNc7C5chjT0DU5Vv6pN/j15fzEB02bfNXed8ayjTMGyJqpzeL2cCv13HJ4153xpA6L/UlrN7PWho83Mhp6oj/WzplCQLf7YXHJwZ7WpEpMO3KNiynTYprZUjsQiZthNQQnYs6A6Raj1XgJZqWyQPqm0yOqyfdoVZDeNRA1ppkJYw6V/sQreBi0U+jE7X4ixz2S/IMSynD5CrVvNnuFhS++vd0beQ=
