language: node_js
node_js:
- '12'
sudo: false
git:
  submodules: false
branches:
  only:
  - master
before_script: make init
script: make build
deploy:
- provider: script
  script: make release
  on:
    branch: master
- provider: script
  script: curl -X POST -d {} https://api.netlify.com/build_hooks/5d53b7e5c624e4e570256c69
  on:
    branch: master
env:
  global:
  - secure: UpMmf4VJdP3z03g8S6FD6qs2Q3sVSHsw+0AJ36R+hnCDq6GHXBVum7HlZDERUwcWVensz973xifYXqfHvwm8KWdpw27QV8gsGS2rMQulYIBQle/Nr8xPtZ9/WtnB35ncvWjVQHUPTTXyrasbsCm8SSJkxjoppSPzoh2wEwsI0gSPI/HiwuytcKqgtvabkG5pkZYb6IA5KebOxO351fQ83tAI1F436xwxE0UK8JZqHBsqgq+LkDxAp0ntqZTsp4ZLp9KNAEZUOxLO40ek1EVo68BVZ+NuPATq39tR2IUPYj5A5UWOJz9/N33XFvbGQiwtk2TDwDw1oQ//4Ip7wdXXIONzI8wYQkqJS+Oq7scyzXPPqqs9ZhldMt46PC8aLDZs2J3NCXhfGLc6gZU/Vrf3nVF/hiDGiHMpdkUoT3/cB84VVXML0+ciWp89zTAiRwppC7IYw+3R7CPITOv4sgl31fVNJIMDOtRrfgbLgmp/D24hH3yCaktNxL7D8eXIVvCxo01MA6uYZNfECPQhiGt1n+i0esPfrJdpH11hTlyxho2hkvS0XoYX+g4d5wEcJKzClSNzpaTtk4nNiLT5uefKP5ZnQegG37//w49GDzcmYpwUUVUm7TSxq6LqSVBmTFVSQPDEIvlrZfMW7tc74+6dm2008D2aWbgB0SW+6f+gxvY=
  - secure: kWwMKU8lmn3RAgr/i5ajKhYWhbSYE5zXYkUBkuFp1AZfGBd2xopxM/yRMjUxCOVAzZF6tF21bx/zwVF3nNHVvMpFBF2a34+Q6nXn2wobeoU3RDw4vnrgoAzVbgE3cyb3k0kgnJjX2MqizBxzxoymSkvtS2An0kjQJ7+etE/zU7/PxNsNFr99fzwWgyAIXVyl/aEHvJVrtJKO90HiePfvbGNGN7q3fUKdbTXUwiIwZNHhEI6zYpbMojPhQPTdeuXsrE2Cx80kiwO7+NjJoZa2xCSGrpj8B94kEmcGrIDfqUP1AelZNJHrnRCNTk2kudqiFJLc4IwlJOOrnGO2NUg8mDTQWTn6ZbD+P5cAdenrqA/tlcsFBmbMVw1OD4RMjumzU11mtpJHBKqtb3UOM3aADYGth4IcV683hIONuYv/wa2VfaDRIMBmZEl2PFSnoaE6u4w/7FCs+wi+8Y4Sj825YYKi5cUFbdyF4FLvV9WSrY1UzZVGWXyHHu5B/qmY+eW4q2Yqko1hg8srciMxfaxucIklSgFczcrOBB4XQsWYvefzdYVLroSZPmeH0pWAjkhl29T3fdl2QksI5fAOtInXSk/dkYbwYr4SDQ0zfgadkemyMKzeQptoZvfNBMNsJo14mVnvqvOgpDDlIWjBxkJMxhOVWbMRbAsBn6Sn+3xEwh8=
  - secure: HnUnNNvaKRZRLPvnlPQA7ynYRQ1vhAOgX/vVwuE6WtmrvFMgwxiFmxZTAzqoYKQXd4OutYJmyPwI69vRFlWg9tLNEG670GKljEGsEytYiGpl8vARpObkZRhHMuBi/eeB5hIw/RkMcZrelNXnLK3fQNsOHRtzraVgtTNvqYW5XZG2Fl0M02YqSAaoG9aPTXsThdfzBoFIlBq7nGr+o3FotSOf1850WTOLdaIEsAHv/f+Qi30zZIb0OOS5YwOXsA7nRvcVSjIOay42kPk8oRbNkvA91tUut5J8VyAXgbDLVYAhGasf0vqY8rqzkXVh+8fFZnw8TQ/2SOvbCtK1aOKEpjCPPvDRKAsYgv/i8IlOnIjRqCoFel2SqTUl15tvEojwGgQ5eP7TrYxuLBSE/7SpuqFpqurMe184R4oOdy/Z/73g1DqpK+s3v9kPMHI4RtKXR7U6dFkwyRb4YGfJGBFHijcn0yQOPma72wwA2LOJvn+AOl82mJWpKKo81IJ/OpQhvrcR+uPNaxW7gNoDQVvNMldUilOkx2V+Y3E0e8DkoUF1G81hosxTjtBvYm1N0JMm3ipSnaqZgYqk693NIqlAQasIi57ijN20EEci1IEXRKZGte6j1amcKCvKo+es3JAZcsR+WllI6Q9r/gmadycqmWoPZDf7vhcdDaquXfmkDBQ=
  - secure: WyrbKoT4B9TzmBGPkJ3FEV95lxu1k+3gIpe4mSZavuESu/B+JKabV/h5TOaDioLzfXSoZGJtDHD3tH2QlVV2K/2qTZ37rqbTIvbbpTBRIXCxt//t6NX1KnTz1cXLmpA+NVgyt0u/p76w6SQ90UhULu/SC/jcmEGIIY8Zk40ln4q1Y6TtIcdjOpe9pX/EU0qZOUWnYNVg0LOS68ZWfJpMZ6TZ9HJmGgbKtn2v3e4pK8cEZnmC2Lo3hnQfknhbGxCzIudvmM53JhNM4KI9iAuli7fyAo9Lf2zR577sL/gtMRzRCAqeAmx/H+UFbyvALd8NIePl3WxQDsCX/UM/yNmv6tAZrKzHIdaVSS36qE3o+KKoWwbrsghS7KQSUXE9EBcNEvCbtnT8cRjki+eoJDWSl/0ub6SNje+LvxwMIJNQJ33RUGyDz8IQ0TOsyVKBUTfoUCXtAcbw/1s4YAXfI6ZyAjd8OLKoWaJmoFcyeDT3G3E7is+oeVJs3TwwDSunQGCECHZqWGDqj6ZqyMr4fm9FnbJ8pltkWFWZHh8jNhMzKdKdXImvsY6ezLZnfeQzyT5iM+u0Of9kFrRShOubgtB8UQVCAWRH8isHIrf7+CVz2nIBnkrtytIL6JsZsLn7BnraRTdyTB0mSVj8N6R05dIQlgUtG8uTp+qOXFTUAj0T6Qw=
